NS_RSM = "urn:un:unece:uncefact:data:standard:CrossIndustryInvoice:100"
NS_UDT = "urn:un:unece:uncefact:data:standard:UnqualifiedDataType:15"
NS_RAM = "urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:12"
NS_QDT = "urn:un:unece:uncefact:data:standard:QualifiedDataType:10"
BASIC = "BASIC"
COMFORT = "COMFORT"
EXTENDED = "EXTENDED"
